name: Playwright autotests run

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose test suite
        required: true
        type: choose
        default: smoke
        options:
          - smoke
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run playwright autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v5
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest -alluredir=allure-results
        continue-on-error: true
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke -alluredir=allure-results
        continue-on-error: true
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz && sudo tar xf /home/user/Downloads/allure-2.35.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.35.1/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c allure-results -o allure-report
      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
            
